services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"   # Redis Server
      - "8001:8001"   # RedisInsight GUI
    volumes:
      - /home/abdaziz/01-volume-data-docker/01-redis-stack:/data
    
volumes:
  redis_data:
    driver: local
